version: "3.1"
services:
    db:
        container_name: mysql
        hostname: mysql
        networks:
            - datasource
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8
        restart: always
        expose:
            - 3306
        ports:
            - 3306:3306
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pretest
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    api-server:
        container_name: api-server
        build: ./server
        image: api-server
        restart: always
        networks:
            - datasource
        expose:
          - 8080
        ports:
            - 8080:8080
        depends_on:
            - db
    web:
        container_name: web
        image: web
        build: ./web
        restart: always
        expose:
          - 3000
        ports:
            - 3000:80

networks:
    datasource:
        driver: bridge
