export const FetchProductActionTypes = {
    FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",
};

export const CreateProductActionTypes = {
    CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
    CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
    CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",
};
