export const FetchInventoryActionTypes = {
    FETCH_INVENTORY_REQUEST: "FETCH_INVENTORY_REQUEST",
    FETCH_INVENTORY_SUCCESS: "FETCH_INVENTORY_SUCCESS",
    FETCH_INVENTORY_FAILURE: "FETCH_INVENTORY_FAILURE",
};

export const CreateInventoryActionTypes = {
    CREATE_INVENTORY_REQUEST: "CREATE_INVENTORY_REQUEST",
    CREATE_INVENTORY_SUCCESS: "CREATE_INVENTORY_SUCCESS",
    CREATE_INVENTORY_FAILURE: "CREATE_INVENTORY_FAILURE",
};
